hf_nli_clf:
  repo_id: "be1pheg0r/hack-mfti-sbercase"
  revision: null
  force_download: false
  trust_remote_code: true
  max_length: 512
  batch_size: 8
  hallucination_threshold: 0.5
  positive_class_index: 1
  compute_dtype: float32

