[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hack-mfti-sber"
version = "0.1.0"
description = "Sber case solution for IT Purple Hack 2026"
requires-python = ">=3.10, <3.13"
readme = "README.md"
dependencies = [
    "colorama",
    "pyyaml",
    "pydantic",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "datasets",
    "torch",
    "transformers",
    "tqdm",
    "rapidfuzz",
    "huggingface-hub",
    "gradio",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "jupyter",
    "optuna",
    "umap-learn",
    "sentence-transformers",
    "accelerate",
]
mistralai = [
    "mistralai",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "common*"]
namespaces = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"

