enabled: true
params:
  n_estimators: 300
  class_weight: balanced_subsample
for_tune:
  n_estimators:
    type: int
    low: 100
    high: 700
    step: 50
  max_depth:
    type: int
    low: 3
    high: 14
    step: 1
  min_samples_split:
    type: int
    low: 2
    high: 20
    step: 1
