enabled: true
params:
  n_estimators: 400
  learning_rate: 0.05
  max_depth: 6
  subsample: 0.9
  colsample_bytree: 0.9
  eval_metric: logloss
  tree_method: hist
  objective: binary:logistic
for_tune:
  n_estimators:
    type: int
    low: 200
    high: 600
    step: 100
  learning_rate:
    type: float
    low: 0.01
    high: 0.2
    log: true
  max_depth:
    type: int
    low: 4
    high: 10
    step: 1
  subsample:
    type: float
    low: 0.7
    high: 1.0
    step: 0.05
  colsample_bytree:
    type: float
    low: 0.7
    high: 1.0
    step: 0.05
